substitutions:
  _BUCKET: 'tf-composer-bucket'

logsBucket: 'cloudbuild-logs-data-composer-artefacts-466417'
timeout: 3600s

steps:

  # 0. Sincroniza DAGs (substitui e remove os não existentes)
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Sincronizando DAGs (substituindo e removendo os não existentes)..."
        gsutil -m rsync -d -r dags gs://$_BUCKET/dags

  # 1. Sincroniza Data
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Sincronizando Data (substituindo os existentes)..."
        gsutil -m rsync -d -r data gs://$_BUCKET/data

  # 2. Sincroniza Logs
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Sincronizando Logs (substituindo os existentes)..."
        gsutil -m rsync -d -r logs gs://$_BUCKET/logs

  # 3. Sincroniza Plugins
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Sincronizando Plugins (substituindo os existentes)..."
        gsutil -m rsync -d -r plugins gs://$_BUCKET/plugins
